# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 01:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 25, 1, 2, 50, 402889, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservedfeature',
            name='reservedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
