# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AlterField(
            model_name='participate',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='building.Poll'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='building.Vote'),
        ),
        migrations.AlterField(
            model_name='role',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='building.Building'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='building.Building'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='building.Poll'),
        ),
    ]
