# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20170729_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manageUser.Account'),
        ),
    ]
