# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('building', '0002_auto_20170727_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='participate',
            name='id',
            field=models.AutoField(auto_created=True, default='2', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='id',
            field=models.AutoField(auto_created=True, default='2', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participate',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Poll'),
        ),
        migrations.AlterField(
            model_name='participate',
            name='vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Vote'),
        ),
        migrations.AlterField(
            model_name='role',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Building'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Building'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Poll'),
        ),
    ]
