# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageUser', '0002_auto_20170729_2202'),
        ('building', '0003_auto_20170729_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('subject', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageUser.Account')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Building')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservedDate', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageUser.Account')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='building.Feature')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='subject',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='subject',
            field=models.CharField(default='nothign', max_length=100),
            preserve_default=False,
        ),
    ]
