# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
