# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageUser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='family',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phoneNumber',
        ),
    ]
