# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='family',
            field=models.CharField(default='nothig', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='nothig', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='phoneNumber',
            field=models.IntegerField(default='158977451'),
            preserve_default=False,
        ),
    ]
